ProjectManager/ViewModels/FeedViewModel.cs
using ProjectManager.Enums;
using ProjectManager.Models;

namespace ProjectManager.ViewModels
{
    public class FeedViewModel
    {
        public string? NomeUsuario { get; set; }
        public string? DescricaoUsuario { get; set; }
        public EnumTipoCargo CargoUsuario { get; set; }

        public string? DescricaoPostagem {get; set;}
        public IEnumerable<PostagemFeed>? Postagens { get; set; }

    }
}

ProjectManager/Controllers/FeedController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectManager.Models;
using ProjectManager.Repositories.Classses;
using ProjectManager.Repositories.Interfaces;
using ProjectManager.ViewModels;

namespace ProjectManager.Controllers
{
    public class FeedController : Controller
    {
        private readonly IFeedRepository _feedRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        public FeedController(IFeedRepository feedRepository, UserManager<ApplicationUser> userManager)
        {
            _feedRepository = feedRepository;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var usuario = _userManager.GetUserAsync(User).Result;

            var feedViewModel = new FeedViewModel
            {
                NomeUsuario = usuario.Nome,
                DescricaoUsuario = usuario.Descricao,
                Postagens = _feedRepository.Postagens.ToList()
            };

            return View(feedViewModel);
        }

        public IActionResult Add(FeedViewModel postagemFeed)
        {
            if (ModelState.IsValid)
            {
                var usuario = _userManager.GetUserAsync(User).Result;

                PostagemFeed postagem = new PostagemFeed
                {
                    Descricao = postagemFeed.DescricaoPostagem,
                    NomeUsuario = usuario.Nome,
                    DataPostagem = DateTime.UtcNow
                };

                _feedRepository.Add(postagem);
                return RedirectToAction("Index");
            }
            return View(postagemFeed);
        }

    }
}

ProjectManager/Views/Feed/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model FeedViewModel;

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

<svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
    <image href="https://jabg-phi.vercel.app/back.jpg" x="0" y="0" height="100%" width="100%" />
</svg>


<h4 class="btn btn-primary" style="width:100%">Descubra novos projetos e entre contato com outros colaboradores!</h4>

<br/><br/>

<div class="container-fluid gedf-wrapper">
    <div class="row">
        
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <div class="h5"></div>
                    <div class="h3 text-muted">@Model.NomeUsuario</div>
                    <div class="h6 text-muted">
                        Descrição: @Model.DescricaoUsuario
                    </div>
                </div>
                @* <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="h6 text-muted">Followers</div>
                        <div class="h5">5.2342</div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6 text-muted">Following</div>
                        <div class="h5">6758</div>
                    </li>
                    <li class="list-group-item">Vestibulum at eros</li>
                </ul> *@
            </div>
        </div>

        <div class="col-md-6 gedf-main">
          
            <!--- \\\\\\\Post-->
            <div class="card gedf-card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
            
                        <li class="nav-item">
                            <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">
                                Faça uma publicação
                            </a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
                        </li> *@
                    </ul>
                </div>
                <form asp-controller="Feed" asp-action="Add" method="post">
                <div class="card-body">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                            <div class="form-group">
                                <label class="sr-only" for="message">post</label>
                                <textarea asp-for="DescricaoPostagem"class="form-control" id="message" rows="3" placeholder="O que você está pensando?"></textarea>
                            </div>

                        </div>
                        <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                            <div class="form-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="customFile">
                                    <label class="custom-file-label" for="customFile">Upload image</label>
                                </div>
                            </div>
                            <div class="py-4"></div>
                        </div>
                    </div>
                    <div class="btn-toolbar justify-content-between">
                       
                            <div class="btn-group">
                                <button type="submit" class="btn btn-primary">Compartilhar</button>
                            </div>
                       
                    </div>
                </div>
                </form>
            </div>
                   
            @foreach (var item in Model.Postagens)
            {
                <!--- \\\\\\\Post-->
                <div class="card gedf-card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>

                    </div>
                    <div class="card-body">
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i> @Html.DisplayFor(modelItem => item.DataPostagem)</div>
                        <a class="card-link" href="#">
                            <h7 class="card-title">@Html.DisplayFor(modelItem => item.NomeUsuario) </h7>
                        </a>

                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.Descricao)
                        </p>
                    </div>
                </div>
                <!-- Post /////-->
            }
        </div>
        <div class="col-md-3">
            <div class="card gedf-card">
                <div class="card-body">
                    <h5 class="card-title">As últimas tendências em Inteligência Artificial</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Como a IA está moldando o futuro da tecnologia</h6>
                    <p class="card-text">
                        A Inteligência Artificial (IA) está rapidamente se tornando uma parte integral de nossas vidas diárias. De assistentes virtuais a carros autônomos, a IA está transformando a maneira como vivemos e trabalhamos. Neste artigo, exploraremos as últimas tendências em IA e como elas estão moldando o futuro da tecnologia. Discutiremos também como as empresas podem se adaptar a essas mudanças e aproveitar as oportunidades oferecidas pela IA. Fique conosco para descobrir mais sobre este tópico fascinante.
                    </p>
                   @*  <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Another link</a> *@
                </div>
            </div>
            
        </div>
    </div>
</div>