ProjectManager/Models/Atividade.cs
using System.ComponentModel.DataAnnotations;

namespace ProjectManager.Models
{
    public class Atividade : PadraoCadastro
    {
        public Dictionary<int, string> Tarefas = new Dictionary<int, string>();

        [Display(Name = "Código do Projeto")]
        public int ProjetoId { get; set; } //O id do projeto será armazenado no banco, mas somente ele

        public virtual Projeto? Projeto { get; set; } //Não vai ser criado na tabela, só será usado para definir o relacionamento entre lanche e categoria
    }
}

ProjectManager/Controllers/AtividadeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectManager.Models;
using ProjectManager.Repositories.Classses;
using ProjectManager.Repositories.Interfaces;
using ProjectManager.ViewModels;

namespace ProjectManager.Controllers
{
    public class AtividadeController : Controller
    {
        private readonly IAtividadeRepository _atividadeRepository;
        private readonly IProjetoRepository _projetoRepository;

        public AtividadeController(IAtividadeRepository atividadeRepository, IProjetoRepository projetoRepository)
        {
            _atividadeRepository = atividadeRepository;
            _projetoRepository = projetoRepository;
        }
        public IActionResult Index()
        {
            var atividadesViewModel = new AtividadeProjetoViewModel
            {
                Atividades = _atividadeRepository.Atividades,
                Projeto = new Models.Projeto()
            };

            return View(atividadesViewModel);
        }

        public IActionResult Create(int idProjeto)
        {
            PopulaViewBags(idProjeto);

            ViewBag.IdProjeto = idProjeto;
            return View();
        }

        public IActionResult Edit(int id)
        {
            var atividade = _atividadeRepository.Atividades.FirstOrDefault(p => p.Id == id);
            if (atividade == null)
            {
                return NotFound();
            }

            PopulaViewBags(atividade.ProjetoId);
            return View(atividade);
        }

        [HttpPost]
        public IActionResult Edit(Atividade atividade)
        {
            if (ModelState.IsValid)
            {
                _atividadeRepository.Update(atividade);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Details", new { id = atividade.ProjetoId });
        }


        [HttpPost]
        public IActionResult Create(Atividade atividade)
        {
            if (ModelState.IsValid)
            {
                PopulaViewBags(atividade.ProjetoId);

                _atividadeRepository.Add(atividade);

                TempData["AtividadeCriada"] = true;

                return RedirectToAction("Details", "Projeto", new { id = atividade.ProjetoId });
            }
            return View(atividade);
        }

        [HttpPost]
        public IActionResult AddIntegrante(string id, Atividade atividade)
        {
            _atividadeRepository.AddIntegrante(id, atividade.Id);

            return View();
        }

        public void PopulaViewBags(int idProjeto)
        {
            var integrantesProjeto = _projetoRepository.ObterIntegrantesPorProjeto(idProjeto) ?? new Dictionary<string, string>();

            ViewBag.IntegrantesProjeto = integrantesProjeto
                                                    .Select(i => new SelectListItem
                                                    {
                                                        Value = i.Key.ToString(),
                                                        Text = i.Value
                                                    })
                                                    .ToList();

        }

        public IActionResult AddIntegrante(string idUsuario, int id)
        {
            _projetoRepository.AddIntegrante(idUsuario, id);

            return RedirectToAction("Edit", new { id = id });
        }

        public IActionResult DeleteIntegrante(string idUsuario, int id)
        {
            _projetoRepository.DeleteIntegrante(idUsuario, id);

            return RedirectToAction("Edit", new { id = id });
        }
    }
}

ProjectManager/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Models;
using ProjectManager.Repositories.Interfaces;
using ProjectManager.ViewModels;

namespace ProjectManager.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public UsuarioController(IUsuarioRepository usuarioRepository)
        {
           _usuarioRepository = usuarioRepository;
        }

        public IActionResult Index(string adicao, int id)
        {
            var usuariosDoRepositorio = _usuarioRepository.Usuarios;

            var usuariosViewModel = usuariosDoRepositorio.Select(usuario => new UsuarioViewModel
            {
                Id = usuario.Id,
                Nome = usuario.Nome,
                TipoCargo = usuario.TipoCargo, 
                Projetos = usuario.Projetos, 
                Email = usuario.Email

            }).ToList();

            ViewBag.Adicao = adicao;
            ViewBag.Id = id;

            return View(usuariosViewModel);
        }


        public ViewResult BuscarUsuario(string id)
        {
            var usuarioRepositorio = _usuarioRepository.GetUsuarioById(id);

            var usuarioViewModel = new UsuarioViewModel
            {
                Nome = usuarioRepositorio.Nome,
                Sobrenome = usuarioRepositorio.Sobrenome,
                Descricao = usuarioRepositorio.Descricao,
                TipoCargo = usuarioRepositorio.TipoCargo, 
                Projetos = usuarioRepositorio.Projetos, 
                Atividades = usuarioRepositorio.Atividades, 
                ValorBolsa = usuarioRepositorio.ValorBolsa,
                Email = usuarioRepositorio.Email,
                Telefone = usuarioRepositorio.PhoneNumber
            };

            return View("Index", usuarioViewModel);
        }
    }
}

ProjectManager/Views/Atividade/Create.cshtml
@model ProjectManager.Models.Atividade

@{
    ViewData["Title"] = "Create";
}

<br/>
<div class="card-header">
<h4>Impulsione seu projeto agora!</h4>
</div>
<br />
<h6>Cadastre sua atividade.</h6>

<div class="row d-flex justify-content-center align-items-center">
    <div class="card text-white bg-success mb-3" style="max-width: 100%;">
        <div class="card-header"><h7>Preencha as informações de cadastro</h7></div>
        <div class="card-body">
            <p class="card-text">
                <div class="col-md-12">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <label asp-for="ProjetoId" class="control-label"></label>
                        <input asp-for="ProjetoId" value="@ViewBag.IdProjeto" readonly class="form-control" />
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                        <div class="form-group">
                            <label asp-for="Descricao" class="control-label"></label>
                            <input asp-for="Descricao" class="form-control" />
                            <span asp-validation-for="Descricao" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DataInicio" class="control-label"></label>
                            <input asp-for="DataInicio" class="form-control" />
                            <span asp-validation-for="DataInicio" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DataTermino" class="control-label"></label>
                            <input asp-for="DataTermino" class="form-control" />
                            <span asp-validation-for="DataTermino" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Responsavel" class="control-label"></label>
                            <select asp-for="Responsavel" asp-items="ViewBag.IntegrantesProjeto as IEnumerable<SelectListItem>" class="form-control">
                                <option value="">Selecione um usuário</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Criar atividade" class="btn btn-primary" />
                            <a class="btn btn-secondary" asp-controller="Projeto" asp-action="Details" asp-route-id="@ViewBag.IdProjeto">Voltar ao projeto</a>
                        </div>
                    </form>
                </div>
            </p>
        </div>
    </div>

</div>

ProjectManager/Views/Atividade/Edit.cshtml
@model ProjectManager.Models.Atividade

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Atividade</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjetoId" class="control-label"></label>
                <select asp-for="ProjetoId" class="form-control" asp-items="ViewBag.ProjetoId"></select>
                <span asp-validation-for="ProjetoId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataTermino" class="control-label"></label>
                <input asp-for="DataTermino" class="form-control" />
                <span asp-validation-for="DataTermino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Responsavel" class="control-label"></label>
                <input asp-for="Responsavel" class="form-control" />
                <span asp-validation-for="Responsavel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Integrantes" class="control-label"></label>
                <select id="opcoes" multiple name="opcoes" asp-for="Integrantes" asp-items="ViewBag.IntegrantesProjeto as IEnumerable<SelectListItem>" class="form-control"></select>
                <input type="hidden" id="opcaoSelecionada" value="" />
                <a id="link" asp-controller="Atividade" asp-action="DeleteIntegrante" asp-route-idUsuario="" asp-route-id=@Model.Id class="btn btn-danger glyphicon glyphicon-remove"></a>
                <a asp-controller="Usuario" asp-action="Index" asp-route-adicao="Atividade" asp-route-id="@Model.Id" class="btn btn-info glyphicon glyphicon-zoom-in"></a>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@{
    var integrantes = ViewBag.IntegrantesProjeto;
}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

<script>
    var integrantes = @Html.Raw(Json.Serialize(integrantes));

    document.getElementById('opcoes').addEventListener('change', function () {
        var opcaoSelecionada = this.options[this.selectedIndex].value;
        var link = document.getElementById('link');
        var url = new URL(link.href);
        url.searchParams.set('idUsuario', opcaoSelecionada);
        link.href = url.toString();
    });
</script>

ProjectManager/Views/Atividade/Index.cshtml
@model AtividadeProjetoViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Projeto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Atividades)
            </th>
           @*  <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataTermino)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Integrantes)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Atividades) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Projeto.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataTermino)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Responsavel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Integrantes)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>